### ISSUE TITLE
UICircularProgressRing class and allowing ability to inherit

### ISSUE THREAD

**Issue by arusa** [luispadron/UICircularProgressRing#188]
## Version

- Version = 6.1.0

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - no
- Please provide as much detail as possible below

Until today I had a subclass of UICircularProgressRing to override the point() method to make it possible to react to a tap on the ring and make sure that the tap was inside the ring.

After updating from 4.1.0 to 6.1.0 this isn't possible anymore, because UICircularProgressRing is now a final class.

This was the code I used up until now:
```
@IBDesignable open class ProgressRingView: UICircularProgressRing {

    override open func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        let border = CGFloat(15.0)
        let innerRadius = bounds.size.width/2 - (border+5)
        let outerRadius = bounds.size.width/2 + (border-5)
        let center = CGPoint(x: bounds.size.width/2, y: bounds.size.height/2)
        let pointRadius = sqrt(pow(center.x-point.x, 2) + pow(center.y-point.y, 2))
        if pointRadius <= outerRadius &&
           pointRadius >= innerRadius {
            return true
        } else {
            return false
        }
    }
```

Is it really necessary that UICircularProgressRing is final?

Is there another recommended way to solve my problem?

Kind regards,
Alex

**Comment by arusa** [comment]
I solved it using extension:

```
extension UICircularProgressRing {

    override public func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
```

The ring-design now isn't how it was before, but I assume I will be able to solve that too.

**Comment by luispadron** [comment]
Hi there, why not use a `UITapGestureRecognizer`? This will be much simpler and more native than what you're doing now. 

As for why `UICircularProgressRing` is final is because it subclasses from a new base class `UICircularRing`, which is the class that should now be subclassed for custom ring drawing, etc.

**Comment by arusa** [comment]
Hi, thanks for the quick reply.

I am using a UITapGestureRecognizer, but I did override point() so that a tap only gets recognized when it hits exactly the ring (and not the whole rectangle of the view).
The ring is used to display the position of an audio playback and after a tap on the ring I calculate where on the ring the tap happened and use the percentage of this position to jump to a position in the audio file.

**Comment by luispadron** [comment]
I see, well then yes the extension you have, in my opinion is better than subclassing. Seems like this is solved, so i’ll be closing the issue. 

Please feel free to reopen if you have more questions.

**Comment by mathieuedet** [comment]
I'm concerned by this final class too. Why did you make this class "final" instead of "open" ? 
Currently, I create a subclass of UICircularProgressRing to create a really custom component from this one but unable to do that just with extensions...

**Comment by ryancrunchi** [comment]
I also would like to be able to subclass this class as long as the properties `minValue`, `maxValue` and `value` are not defined in `UICircularRing` and therefore can not be overridden.

```
class CircularProgressTrackerView: UICircularRing {
// class CircularProgressTrackerView: UICircularProgressRing cannot inherit from final class

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        commonInit()
    }

    override init(frame: CGRect) {
        super.init(frame: frame)
        commonInit()
    }
    
    var progress: Progress {
        didSet {
            minValue = 0 // Use of unresolved identifier 'minValue'
            maxValue = CGFloat(progress.totalUnitCount) // Use of unresolved identifier 'maxValue'
            value = CGFloat(progress.completedUnitCount) // Use of unresolved identifier 'value'
            // pseudo observable closure
            progress.didUpdate = { self.value = $0 }
        }
    }

    private func commonInit() {
        maxValue = 1 // Use of unresolved identifier 'maxValue'
    }
}
```

**Comment by luispadron** [comment]
I understand where the confusion might be coming from.

For the latest major release, in order to reuse code and add support for a new "timer" ring. I refactor the `UICircularProgressRing` class from v4.0 and below into two classes. `UICircularRing` and `UICircularProgressRing`. 

This library offers two "concrete" classes, that is `UICircularProgressRing` and `UICircularTimerRing` which both inherit from `UICircularRing`. These concrete classes are marked as `final`, since any customization should be done via the API (which was also refactored) and not by subclassing. 

However, this does not stop anyone from creating a custom "ring" class. The base class is still there and is called "UICircularRing". Looking at the source for `UICircularProgressRing.swift` might help with understanding how this new API is intended to work.

Again, this was done in order to allow a common central point for abstraction. Since a timer doesn't require properties that might be needed for a progress ring of sorts. 

I would be open to further discussion on this and as such will be reopening this.

**Comment by ryancrunchi** [comment]
Sorry to comment this closed issue again, but the use case I described above is still a valid use case and is not resolved with UICircularRing class as it does not have the properties I need from UICircularProgressRing. If you don’t want us to subclass, please provide a way to access the concrete classes features (via protocol ?)

**Comment by luispadron** [comment]
Thats because those properties are not part of `UICircularRing` or `UICiruclarProgressRing`. They are internal to `UICiruclarRingLayer`. I see what you mean though, the `ringLayer` property is internal because the layer class itself is internal. I will release an update when I get a chance which makes that layer public.
